version: '3.2'
services:
  solr:
    image: solr:9.5.0-slim
    ports:
      - "8983:8983"
   # volumes:
      #- ./data:/var/solr
    command:
      - solr-precreate
      - restaurants
  restaurant-service:
    build:
      context: ./restaurant-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - solr
  init-data:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/scripts
    depends_on:
      - solr
    command: [ "sh", "/scripts/startup.sh" ]
volumes:
  data:
  scripts: