version: '3.8'
services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: service_pass
    ports:
      - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: on-failure
volumes:
  postgres-data: {}